### PR TITLE
Escape unmanaged mod names

### PR DESCRIPTION
**Pull request by LostDragonist**
Yes, this code kills my soul.

### CODE REVIEW

**Comment by Holt59** [comment]
Let me check that one before merging.

**Comment by Holt59** [comment]
Ok I though `QRegularExpression::wildcardToRegularExpression` would work but actually the problem is not that the pattern is a regex but rather a glob, and `[ab]` is a valid glob pattern.

`escapeModName` should probably be renamed `escapeGlobPattern` and also handles `?` although this one is probably less problematic (problematic only if you have two mods, one with `?` and one with a character other than `?` at the same place).

Oh, and of course there are no easy function to escape glob patterns in Qt...

**Comment by LostDragonist** [comment]
? is also less of a problem as it's not a valid character for Windows filenames.  Though probably best to add it anyways.

**Comment by LostDragonist** [comment]
And, of course, I need to check the rest of MO's code for similar problems.  This was just a quick fix over my lunch break. :D

**Pull request closed without merging**
